# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Luccas Bonato
tagline:             'GitHub'
description:         'Meu nome é <a href="https://www.linkedin.com/in/luccas-bonato-36958411a/" target="_blank">Luccas Bonato</a>. Eu sou um estudante de Engenharia Elétrica da UFRN e estou aqui criando coisas úteis para a web ou não. Kappa.'
url:                 # http://lanyon.getpoole.com
baseurl:             ''
# paginate:            5

# About/contact
author:
  name:              Luccas Bonato
  url:               https://www.linkedin.com/in/luccas-bonato-36958411a/
  email:             las-9@hotmail.com

# Custom vars
version:             1.0.0

include: [PDI]
